# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'sinix'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9901']

  - job_name: 'systemd-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9903']

  - job_name: 'smartctl-exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['host.docker.internal:9905']

  - job_name: zfs_exporter
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 60s
    static_configs:
      - targets: [host.docker.internal:9902] 
    metric_relabel_configs:
      - source_labels: ['name']
        regex: ^([^@]*).*$
        target_label: filesystem
        replacement: ${1}
      - source_labels: ['name']
        regex: ^.*:.._(.*)$
        target_label: snapshot_type
        replacement: ${1}

  - job_name: 'home-assistant'
    scrape_interval: 15s
    metrics_path: /api/prometheus
    authorization:
      type: 'Bearer'
      credentials_file: 'secrets/prometheus_homeassist_token'
    scheme: https
    static_configs:
      - targets: ['homeassistant.sinet.uk']