#!/bin/sh

# Simple helper script to invoke docker-compose on a service stack with all the env variable files included (secrets.env, shared.env and <service>/settings.env)

servicesdir=$(dirname "$0")
targetdir="$servicesdir/$1"

if [[ -f $targetdir/settings.env ]]; then
   settings_arg="--env-file $targetdir/settings.env"
else
   settings_arg=
fi

docker-compose --project-directory $targetdir --env-file /etc/nixos/secrets/secrets.env --env-file $servicesdir/shared.env $settings_arg "${@:2}"
